CREATE TABLE `operators` (
	`id` INT NOT NULL COMMENT '主键',
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`department` VARCHAR(255) COMMENT '部门',
	`employee_id` VARCHAR(255) COMMENT '员工ID',
	`name` VARCHAR(255) NOT NULL COMMENT '姓名',
	`position` VARCHAR(255) COMMENT '职位',
	`status` TINYINT COMMENT '状态',
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT '操作员表';